version: 2
jobs:
  build:
    docker:
      - image: cimg/base:2020.01

    working_directory: ~/src

    steps:
      - checkout

      - setup_remote_docker:
          version: 18.06.0-ce
      
      - run:
          name: run tests
          command: |
            docker image build -t fitter-happier-docker web
            docker container run fitter-happier-docker python -m unittest

      - store_artifacts:
          path: test-reports
          destination: test-reports

  publish-image:
    docker:
      - image: cimg/base:2020.01

    steps:
      - checkout

      - setup_remote_docker:
          version: 18.06.0-ce

      - deploy:
          name: Publish application to Docker Hub
          command: |
            echo "$DOCKER_HUB_PWD" | docker login --username $DOCKER_HUB_USER_ID --password-stdin
            docker image build -t fitter-happier-docker web
            docker tag fitter-happier-docker $DOCKER_HUB_USER_ID/fitter-happier-docker:$CIRCLE_SHA1
            docker tag fitter-happier-docker $DOCKER_HUB_USER_ID/fitter-happier-docker:latest
            docker push $DOCKER_HUB_USER_ID/fitter-happier-docker:$CIRCLE_SHA1
            docker push $DOCKER_HUB_USER_ID/fitter-happier-docker:latest

# orchestrate or schedule a set of jobs
workflows:
  version: 2
  # name the workflow "build-master" (a bit of a misnomer, because it does NOT just build on master)
  build-master:
    jobs:
      - build
      - publish-image:
          requires:
            - build
          filters:
            # publishing an image only happens when we're on master
            branches:
              only: master
